import { Datasource } from '@/domain/datasources';
import dayjs from 'dayjs';

const datasources = [
  {
    id: 'USR-010',
    name: 'datasource -1',
    icon: '/assets/avatar-10.png',
    alias: 'alcides.antonio@devias.io',
    type: '908-691-3242',
    version: '1.0.0',
    // address: { city: 'Madrid', country: 'Spain', state: 'Comunidad de Madrid', street: '4158 Hedge Street' },
    createdAt: dayjs().subtract(2, 'hours').toDate(),
  },
  {
    id: 'USR-009',
    name: 'Marcus Finn',
    icon: '/assets/avatar-9.png',
    alias: 'marcus.finn@devias.io',
    type: '415-907-2647',
    version: '1.0.0',
    // address: { city: 'Carson City', country: 'USA', state: 'Nevada', street: '2188 Armbrester Drive' },
    createdAt: dayjs().subtract(2, 'hours').toDate(),
  },
  {
    id: 'USR-008',
    name: 'Jie Yan',
    icon: '/assets/avatar-8.png',
    alias: 'jie.yan.song@devias.io',
    type: '770-635-2682',
    version: '1.0.0',
    // address: { city: 'North Canton', country: 'USA', state: 'Ohio', street: '4894 Lakeland Park Drive' },
    createdAt: dayjs().subtract(2, 'hours').toDate(),
  },
  {
    id: 'USR-007',
    name: 'Nasimiyu Danai',
    icon: '/assets/avatar-7.png',
    alias: 'nasimiyu.danai@devias.io',
    type: '801-301-7894',
    version: '1.0.0',
    // address: { city: 'Salt Lake City', country: 'USA', state: 'Utah', street: '368 Lamberts Branch Road' },
    createdAt: dayjs().subtract(2, 'hours').toDate(),
  },
  {
    id: 'USR-006',
    name: 'Iulia Albu',
    icon: '/assets/avatar-6.png',
    alias: 'iulia.albu@devias.io',
    type: '313-812-8947',
    version: '1.0.0',
    // address: { city: 'Murray', country: 'USA', state: 'Utah', street: '3934 Wildrose Lane' },
    createdAt: dayjs().subtract(2, 'hours').toDate(),
  },
  {
    id: 'USR-005',
    name: 'Fran Perez',
    icon: '/assets/avatar-5.png',
    alias: 'fran.perez@devias.io',
    type: '712-351-5711',
    version: '1.0.0',
    // address: { city: 'Atlanta', country: 'USA', state: 'Georgia', street: '1865 Pleasant Hill Road' },
    createdAt: dayjs().subtract(2, 'hours').toDate(),
  },

  {
    id: 'USR-004',
    name: 'Penjani Inyene',
    icon: '/assets/avatar-4.png',
    alias: 'penjani.inyene@devias.io',
    type: '858-602-3409',
    version: '1.0.0',
    // address: { city: 'Berkeley', country: 'USA', state: 'California', street: '317 Angus Road' },
    createdAt: dayjs().subtract(2, 'hours').toDate(),
  },
  {
    id: 'USR-003',
    name: 'Carson Darrin',
    icon: '/assets/avatar-3.png',
    alias: 'carson.darrin@devias.io',
    type: '304-428-3097',
    version: '1.0.0',
    // address: { city: 'Cleveland', country: 'USA', state: 'Ohio', street: '2849 Fulton Street' },
    createdAt: dayjs().subtract(2, 'hours').toDate(),
  },
  {
    id: 'USR-002',
    name: 'Siegbert Gottfried',
    icon: '/assets/avatar-2.png',
    alias: 'siegbert.gottfried@devias.io',
    type: '702-661-1654',
    version: '1.0.0',
    // address: { city: 'Los Angeles', country: 'USA', state: 'California', street: '1798 Hickory Ridge Drive' },
    createdAt: dayjs().subtract(2, 'hours').toDate(),
  },
  {
    id: 'USR-001',
    name: 'Miron Vitold',
    icon: '/assets/avatar-1.png',
    alias: 'miron.vitold@devias.io',
    type: '972-333-4106',
    version: '1.0.0',
    // address: { city: 'San Diego', country: 'USA', state: 'California', street: '75247' },
    createdAt: dayjs().subtract(2, 'hours').toDate(),
  },
] satisfies Datasource[];

export async function getDatasources(offset: number = 0, pageSize: number = 10): Promise<Datasource[]> {
  return datasources.slice(offset, offset + pageSize);
}
